### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by kristinnmayo** [kristinnmayo/go-practice#1]
- [x] permissions check
- [x] separate functions from main
- [ ] go/flags
- [ ] extend functionality - command line options
- [ ] improve output formatting
- [ ] check all char cases (upper/lower)
- [ ] clean up/make more efficient
- [x] turn todo list into issues
