### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by kristinnmayo** [kristinnmayo/go-practice#2]
- [x] permissions check
- [x] separate functions from main
- [ ] go/flags
- [ ] extend functionality - command line options
- [ ] improve output formatting
- [ ] check all char cases (upper/lower)
